# Generated by Django 4.1.5 on 2023-01-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
