# Generated by Django 4.1.5 on 2023-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
