# Generated by Django 4.2 on 2023-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.CharField(default='', max_length=50),
        ),
    ]
