# Generated by Django 4.2 on 2023-05-02 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_category_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_information',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
