# Generated by Django 4.2.3 on 2023-09-11 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('total', models.IntegerField(default=0)),
                ('lastname', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('firstname', models.CharField(max_length=255, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('another_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Autre téléphone')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('delivery_address', models.CharField(max_length=512, verbose_name='Adresse de livraison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Commande d'utilisateur",
                'verbose_name_plural': "Commandes d'utilisateurs",
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('total', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
