# Generated by Django 4.2.3 on 2023-09-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_orderorder_ordereditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderorder',
            name='total',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.orderorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderorder',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
