# Generated by Django 4.2.3 on 2023-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_orderorder_price_remove_orderorder_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
