# Generated by Django 4.2.3 on 2023-09-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_cart_ordered_cart_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
