# Generated by Django 4.2.3 on 2023-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_cart_ordered_remove_cart_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderorder',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
