# Generated by Django 4.2.3 on 2023-09-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_orderorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderorder',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='Methode de paiement'),
        ),
    ]
