# Generated by Django 5.0.6 on 2024-06-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_orderorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderorder',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
