# Generated by Django 5.0.6 on 2024-06-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_orderorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
