# Generated by Django 5.0.6 on 2024-06-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_orderorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderorder',
            name='order_item',
        ),
    ]
