# Generated by Django 5.0.6 on 2024-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='orders',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
