# Generated by Django 5.0.6 on 2024-07-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_whishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlistitem',
            old_name='product',
            new_name='products',
        ),
    ]
