# Generated by Django 5.0.6 on 2024-07-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_rename_product_whishlistitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlistitem',
            old_name='products',
            new_name='product',
        ),
    ]
