# Generated by Django 4.2.3 on 2023-07-13 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shopper_birthdate_alter_shopper_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
    ]
