# Generated by Django 4.1.5 on 2023-01-29 18:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from=['name']),
            preserve_default=False,
        ),
    ]
