# Generated by Django 4.1.5 on 2023-01-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
