# Generated by Django 4.1.5 on 2023-02-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
